db_file: "bot.db"

bot_url: "https://t.me/PocketerSimpleBot"

messages:
  responses:
    start: "Hi! To save your links in a Pocket account you should give me an access for this. Follow the link:\n%s"
    already_authorized: "You are already authorized. Send me a link I will save!"
    saved_successfully: "Link saved successfully."
    unknown_command: "I don't know this commmand! Please re-enter."
  errors:
    default: "Unknown error"
    invalid_url: "This link is not valid!"
    unauthorized: "You are not authorized! Use commmand /start"
    unable_to_save: "Link has not saved. Try again later"

commands:
  start: "start"
